
import "./perfil_comerciante/Perfil_comerciante.css"
import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css'
import Script from "next/script";
import LayoutWrapper from "./components/Pag_sem_menu_lateral"
import "bootstrap-icons/font/bootstrap-icons.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="pt">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

    

        <LayoutWrapper>
          {children}
        </LayoutWrapper>


        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" />

      </body>
    </html>
  );
}
  